# Generated by Django 5.1.7 on 2025-04-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergie',
            name='gravite',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='allergie',
            name='traitement',
            field=models.TextField(),
        ),
    ]
